# Prometheus config for the all-in-one container. The DNS-collector exporter is
# on localhost (same container).
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: lab
    monitor: dnstap2

scrape_configs:
  - job_name: dnscollector
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9599"]
        labels:
          source: dnscollector

  - job_name: prometheus_self
    static_configs:
      - targets: ["localhost:9090"]
